name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  Atelier:
    permissions:
      contents: read
      # So skipped-attribute checks can be posted.
      checks: write

    uses: JuneStepp/atelier/.github/workflows/discover.yaml@4a94601e6fa41e8fb599e5938b51e9d988b1564d
    with:
      repository: JuneStepp/atelier
      ref: 4a94601e6fa41e8fb599e5938b51e9d988b1564d

    secrets:
       CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
       CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
